imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: sonata.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

sensio_framework_extra:
    view:    { annotations: false }

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        less:
            node: %nodejs.path%
            node_paths: [%nodejs.modules_path%]
            apply_to: "\.less$"
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine_mongodb:
    connections:
        default:
            server: mongodb://%database_host%:%database_port%
            options: {}
    default_database: %database_name%
    document_managers:
        default:
            auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_user:
    db_driver: mongodb
    firewall_name: main
    user_class: Che\CheLoreBundle\Document\User
    registration:
        confirmation:
            enabled:    false
#            from_email:
#                address:        %user_confirmation_address%
#                sender_name:    %user_confirmation_sender%

fos_rest:
    view:
        view_response_listener: force
    format_listener:
        rules:
            - { path: '^/', priorities: ['json', 'xml', 'html'], fallback_format: json, prefer_extension: false }

nelmio_api_doc:
    name: Che Testing System

stof_doctrine_extensions:
    mongodb:
        default:
            sluggable: true
            timestampable: true

braincrafted_bootstrap:
    jquery_path: %kernel.root_dir%/../web/assets/jquery/dist/jquery.js
