sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]
        # Your other blocks

sonata_admin:
    title:      GeekHub Lore
#    title_logo: img/logo_small.png
    templates:
        layout: CheLoreBundle:admin:standard_layout.html.twig
